### PR TITLE
Extracted: Repository methods to traits (fixes #140)

### LINKED ISSUE #140: Extract repository methods to traits
If you extract the concrete methods in the repositories to traits it would be easier to use the plugin, i.e. you could just `use` the trait and implement the interface and you would be good to go. Now you have to copy the method manually.

### PR DESCRIPTION
**Pull request by igormukhingmailcom**

### CODE REVIEW

**Comment by igormukhingmailcom** [comment]
Thanks, @lchrusciel 
Will be great to have this pr merged and tagged...

**Comment by lchrusciel** [comment]
But the build is red :(

**Comment by lchrusciel** [comment]
I'm also considering if more query specific class wouldn't be a better solution, but it is a broader topic.

**Comment by igormukhingmailcom** [comment]
> But the build is red :(
I have feeling the reason of red builds somewhere outside of my PR (kinda tests failed after upgrade to 1.6).
This is PR of another author which have exactly same errors at travis: https://travis-ci.org/Sylius/AdminOrderCreationPlugin/jobs/645853418#L1036

**Comment by igormukhingmailcom** [comment]
`master` branch was green at Nov 22, 2019 but not now.
I've created PR from `master` and have same errors: https://travis-ci.org/Sylius/AdminOrderCreationPlugin/jobs/658827291#L1061

So once master will be fixed - I will rebase my branch and it will be ready to be merged.

**Comment by gabiudrescu** [comment]
@lchrusciel any chances this get merged to Master anytime soon?

currently, if someone is using this plugin together with another plugin that requires methods in the EntityRepository it fails with a pretty obscure error like the one below:

```
[2020-03-23 17:49:07] messenger.ERROR: Error thrown while handling message Setono\SyliusMailchimpPlugin\Message\Command\RepushCustomers. Sending for retry #3 using 4000 ms delay. Error: "Argument 1 passed to Setono\SyliusMailchimpPlugin\Message\Handler\RepushCustomersHandler::__construct() must be an instance of Setono\SyliusMailchimpPlugin\Doctrine\ORM\CustomerRepositoryInterface, instance of Sylius\AdminOrderCreationPlugin\Doctrine\ORM\CustomerRepository given, called in /srv/sylius/var/cache/dev/ContainerE2kvtse/getSetonoSyliusMailchimp_Message_Handler_RepushCustomersService.php on line 12" {"message":"[object] (Setono\\SyliusMailchimpPlugin\\Message\\Command\\RepushCustomers: {})","class":"Setono\\SyliusMailchimpPlugin\\Message\\Command\\RepushCustomers","retryCount":3,"delay":4000,"error":"Argument 1 passed to Setono\\SyliusMailchimpPlugin\\Message\\Handler\\RepushCustomersHandler::__construct() must be an instance of Setono\\SyliusMailchimpPlugin\\Doctrine\\ORM\\CustomerRepositoryInterface, instance of Sylius\\AdminOrderCreationPlugin\\Doctrine\\ORM\\CustomerRepository given, called in /srv/sylius/var/cache/dev/ContainerE2kvtse/getSetonoSyliusMailchimp_Message_Handler_RepushCustomersService.php on line 12","exception":"[object] (TypeError(code: 0): Argument 1 passed to Setono\\SyliusMailchimpPlugin\\Message\\Handler\\RepushCustomersHandler::__construct() must be an instance of Setono\\SyliusMailchimpPlugin\\Doctrine\\ORM\\CustomerRepositoryInterface, instance of Sylius\\AdminOrderCreationPlugin\\Doctrine\\ORM\\CustomerRepository given, called in /srv/sylius/var/cache/dev/ContainerE2kvtse/getSetonoSyliusMailchimp_Message_Handler_RepushCustomersService.php on line 12 at /srv/sylius/vendor/setono/sylius-mailchimp-plugin/src/Message/Handler/RepushCustomersHandler.php:21)"} []
```

**Comment by lchrusciel** [comment]
Hey Igor and Gabi 👋 
I will ask Magda, to put it to the next sprint, so where will be much higher chance, that someone will pick it up. 
Thanks for heads up ;)

**Comment by lchrusciel** [comment]
If, in any case this is still relevant to you, please rebase to the newest master and if green I will merge it.

**Comment by gabiudrescu** [comment]
in case this wasn't solved by some other commit, I find it very relevant, as this prevents the usage of this plugin together with other plugins, which makes the entire plugin ecosystem become irrelevant...

**Comment by gabiudrescu** [comment]
if no one shows some love to this PR, I'll give it a go this weekend and maybe try to fix it myself

**Comment by igormukhingmailcom** [comment]
@lchrusciel , its green. Could you merge and release please?

**Comment by igormukhingmailcom** [comment]
@lchrusciel, this one looks good?

**Comment by lchrusciel** [comment]
Thanks, Igor! :tada:

**Pull request merged**
