### PR TITLE
Copy templates before running tests

### PR DESCRIPTION
**Pull request by Zales0123**
Benefits of this change:
- we don't need to remember to change/add two templates (in a plugin and test application)
- we don't have these templates duplicated in the repository
- it reflects the behavior of developer that installs this plugin

### CODE REVIEW

**Comment by GSadee** [comment]
But if I understand that correctly, it will work only for travis, what with local environment?

**Comment by Zales0123** [comment]
Yeah, this is the drawback, I have not thought about 😄 it depends what we want more, having duplicated templates in repo or being forced to copy them manually on our local environments (maybe we should add the folder to `.gitignore`, just keep the `.gitkeep` file)

**Comment by pamil** [comment]
Why do we need those templates in the first place?

**Comment by Zales0123** [comment]
Not relevant right now, maybe we can do it in the future :)

**Pull request closed without merging**
